---
- name: install node-export and cadvisor
  hosts: ['vps1','vps2','vps3']
  become: true
  gather_facts: false
  roles:
    - node-export-cadvisor

- name: install prometheus to localhost
  hosts: localhost
  become: true
  gather_facts: false
  roles:
    -  prometheus

- name: install alert servers
  hosts: all
  become: true
  gather_facts: false
  roles:
   - alertmanager

- name: install grafana
  hosts: localhost
  become: true
  gather_facts: false
  roles:
   - grafana